<?php

/** @var \Magento\Customer\Block\Address\Edit $block */

use ProcessEight\AddCustomerAddressEavAttributeExample\Api\ProcesseightAddressNicknameInterface;
?>
<div class="field <?= ProcesseightAddressNicknameInterface::CODE ?>> ">
    <label class="label" for="<?= ProcesseightAddressNicknameInterface::CODE ?>"><span><?= $block->escapeHtml(__(ProcesseightAddressNicknameInterface::LABEL)) ?></span></label>
    <div class="control">
        <input type="text"
               name="<?= ProcesseightAddressNicknameInterface::CODE ?>"
               value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
               title="<?= $block->escapeHtmlAttr(__(ProcesseightAddressNicknameInterface::LABEL)) ?>"
               class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass(ProcesseightAddressNicknameInterface::CODE)) ?>"
               id="<?= ProcesseightAddressNicknameInterface::CODE ?>>">
    </div>
</div>
