<?php
/**
 * Copyright © ProcessEight. All rights reserved.
 */
/**
 * This template adds a message above the order grid.
 * This template is rendered by the sales.order.history.info.introduction block,
 * which is declared in htdocs/app/code/ProcessEight/CustomiseMyAccountOrderHistoryExample/view/frontend/layout/sales_order_history.xml:16
 */
?>
<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<p>In this section you can view all your recent orders.</p>
